FROM oven/bun:1.2

WORKDIR /workspace

COPY package.json bun.lock tsconfig.json tsconfig.base.json ./
COPY packages/n2/package.json ./packages/n2/package.json
COPY examples/order/package.json ./examples/order/package.json
COPY services/profile-provider/package.json ./services/profile-provider/package.json
COPY services/request-provider/package.json ./services/request-provider/package.json

RUN bun install --frozen-lockfile

COPY packages ./packages
COPY examples ./examples
COPY services ./services

ENV NODE_ENV=production
